const cosmetcisData = [
  {
    brandName: "Lush",
    productName: "Ocean Salt Scrub",
    category: "Skincare",
    location: "Shelf 1",
    price: 29.95,
    manufactureDate: new Date(2022, 0, 15),
    expirationDate: new Date(2024, 0, 15),
    comments: "Best seller",
  },
  {
    brandName: "Clinique",
    productName: "Moisture Surge",
    category: "Skincare",
    location: "Shelf 2",
    price: 49.5,
    manufactureDate: new Date(2022, 3, 10),
    expirationDate: new Date(2025, 3, 10),
    comments: "For sensitive skin",
  },
  {
    brandName: "MAC",
    productName: "Studio Fix Fluid",
    category: "Makeup",
    location: "Shelf 3",
    price: 31.0,
    manufactureDate: new Date(2023, 1, 1),
    expirationDate: new Date(2026, 1, 1),
    comments: "Long-lasting foundation",
  },
  {
    brandName: "Estee Lauder",
    productName: "Advanced Night Repair",
    category: "Skincare",
    location: "Shelf 4",
    price: 100.0,
    manufactureDate: new Date(2022, 11, 25),
    expirationDate: new Date(2024, 11, 25),
    comments: "Anti-aging serum",
  },
  {
    brandName: "Neutrogena",
    productName: "Hydro Boost Water Gel",
    category: "Skincare",
    location: "Shelf 5",
    price: 21.49,
    manufactureDate: new Date(2023, 5, 15),
    expirationDate: new Date(2025, 5, 15),
    comments: "Hydrating moisturizer",
  },
];
module.exports = cosmetcisData;
